apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
spec:
  accessModes:
    - ReadWriteOnce            # or ReadWriteMany if supported
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard 

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: model-trainer-job
spec:
  schedule: "* * * * *" # TODO: implement a cron spec that runs every 1-2 minutes
  concurrencyPolicy: Forbid  # Don't start new job if previous still running
  successfulJobsHistoryLimit: 5         # keep only 5 (keep disk util low)
  failedJobsHistoryLimit: 1             # keep no more than 5 (keep disk util low)    
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 600       # delete Job 10 minutes after it finishes
      template:
        metadata:
          labels:
            app: model-trainer
        spec:
          containers:
          - name: model-trainer
            # TODO: Replace <DockerHub-Username> with your Docker Hub username, and use the appropriate image name and tag
            image: speddaka/ml-trainer:1.0.0
            volumeMounts:
            - name: model-volume
              mountPath: /shared-volume
          volumes:
          - name: model-volume
            persistentVolumeClaim:
              claimName: model-pvc
          terminationGracePeriodSeconds: 30
          restartPolicy: OnFailure              